### ISSUE TITLE
does this grpcgen-docker is still working?

### ISSUE THREAD

**Issue by Jeffchiucp** [indeedeng-alpha/grpcgen-docker#3]
I was wondering who manage the docker container images?

I would like to avoid issue and trying to figure out why my compiled code would not be running. 

Appreciate your support.

**Comment by mjpitz** [comment]
Hey @jeffchiucp I used to manage the project and haven't contributed to this in a long time. It's probably safe to say that while this may work, there are a lot of dated things about it. In more recent projects, I've had a lot of success doing this on a case by case basis. If you'd like a newer reference, you can take a look at the https://github.com/depscloud/api project which has builder images for go and python.

**Comment by Jeffchiucp** [comment]
appreciate your help. This is really helpful to know.

**Comment by mjpitz** [comment]
@DuaneOBrien I no longer have my super user perms.. mind archiving this project?
